SparkAuto5/Models/ServiceType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SparkAuto5.Models
{
    public class ServiceType
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public double Price { get; set; }
    }
}

SparkAuto5/Pages/Cars/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SparkAuto5.Data;
using SparkAuto5.Models;

namespace SparkAuto5.Pages.Cars
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Car Car { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        public IActionResult OnGet(string userId = null)
        {
            Car = new Car();
            if (userId is null)
            {
                var claimsIdenitity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdenitity.FindFirst(ClaimTypes.NameIdentifier);
                userId = claim.Value;
            }
            Car.UserId = userId;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            StatusMessage = "Car has been added successfully!";
            _db.Car.Add(Car);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index", new { userId = Car.UserId });
        }
    }
}

SparkAuto5/Pages/ServiceTypes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SparkAuto5.Data;
using SparkAuto5.Models;
using SparkAuto5.Utility;

namespace SparkAuto5.Pages.ServiceTypes
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public ServiceType ServiceType { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _db.ServiceType.Add(ServiceType);
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");
        }
    }
}

SparkAuto5/Pages/ServiceTypes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SparkAuto5.Data;
using SparkAuto5.Models;
using SparkAuto5.Utility;

namespace SparkAuto5.Pages.ServiceTypes
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public DetailsModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public ServiceType ServiceType { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ServiceType = await _db.ServiceType.FirstOrDefaultAsync(m => m.Id == id);

            if (ServiceType == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

SparkAuto5/Pages/Services/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SparkAuto5.Data;
using SparkAuto5.Models;
using SparkAuto5.Models.ViewModel;
using SparkAuto5.Utility;

namespace SparkAuto5.Pages.Services
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public CarServiceViewModel CarServiceViewModel { get; set; }

        public async Task<IActionResult> OnGetAsync(int? carId)
        {
            CarServiceViewModel = new CarServiceViewModel
            {
                Car = await _db.Car.Include(c => c.ApplicationUser).FirstOrDefaultAsync(c => c.Id == carId),
                ServiceHeader = new Models.ServiceHeader()
            };

            List<String> listServiceTypeInShoppingCart = _db.ServiceShoppingCart
                .Include(c => c.ServiceType)
                .Where(c => c.CarId == carId)
                .Select(c => c.ServiceType.Name)
                .ToList();

            IQueryable<ServiceType> listService = from s in _db.ServiceType
                                                  where !(listServiceTypeInShoppingCart.Contains(s.Name))
                                                  select s;
            CarServiceViewModel.ServiceTypesList = listService.ToList();
            CarServiceViewModel.ServiceShoppingCart = _db.ServiceShoppingCart.Include(c => c.ServiceType).Where(c => c.CarId == carId).ToList();
            CarServiceViewModel.ServiceHeader.TotalPrice = CarServiceViewModel.ServiceShoppingCart.Sum(item => item.ServiceType.Price);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                CarServiceViewModel.ServiceHeader.DateAdded = DateTime.Now;
                CarServiceViewModel.ServiceShoppingCart = _db.ServiceShoppingCart.Include(c => c.ServiceType).Where(c => c.CarId == CarServiceViewModel.Car.Id).ToList();
                CarServiceViewModel.ServiceHeader.TotalPrice = CarServiceViewModel.ServiceShoppingCart.Sum(s => s.ServiceType.Price);
                CarServiceViewModel.ServiceHeader.CarId = CarServiceViewModel.Car.Id;

                _db.ServiceHeader.Add(CarServiceViewModel.ServiceHeader);
                await _db.SaveChangesAsync();

                foreach (var detail in CarServiceViewModel.ServiceShoppingCart)
                {
                    ServiceDetails serviceDetails = new ServiceDetails
                    {
                        ServiceHeaderId = CarServiceViewModel.ServiceHeader.Id,
                        ServiceName = detail.ServiceType.Name,
                        ServicePrice = detail.ServiceType.Price,
                        ServiceTypeId = detail.ServiceTypeId
                    };

                    _db.ServiceDetails.Add(serviceDetails);
                }
                _db.ServiceShoppingCart.RemoveRange(CarServiceViewModel.ServiceShoppingCart);
                await _db.SaveChangesAsync();
                return RedirectToPage("../Cars/Index", new { userId = CarServiceViewModel.Car.UserId});
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAddToCart()
        {
            ServiceShoppingCart objServiceCart = new ServiceShoppingCart()
            {
                CarId = CarServiceViewModel.Car.Id,
                ServiceTypeId = CarServiceViewModel.ServiceDetails.ServiceTypeId
            };
            _db.ServiceShoppingCart.Add(objServiceCart);
            await _db.SaveChangesAsync();
            return RedirectToPage("Create", new { carId = CarServiceViewModel.Car.Id });
        }

        public async Task<IActionResult> OnPostRemoveFromCart(int serviceTypeId)
        {
            ServiceShoppingCart objServiceCart = _db.ServiceShoppingCart
                .FirstOrDefault(u => u.CarId == CarServiceViewModel.Car.Id && u.ServiceTypeId == serviceTypeId);
            _db.ServiceShoppingCart.Remove(objServiceCart);
            await _db.SaveChangesAsync();
            return RedirectToPage("Create", new { carId = CarServiceViewModel.Car.Id });
        }
    }
}

SparkAuto5/Pages/Services/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SparkAuto5.Data;
using SparkAuto5.Models;

namespace SparkAuto5.Pages.Services
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public DetailsModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public ServiceHeader ServiceHeader { get; set; }
        public List<ServiceDetails> ServiceDetails { get; set; }
        public void OnGet(int serviceId)
        {
            ServiceHeader = _db.ServiceHeader.Include(s => s.Car).Include(s => s.Car.ApplicationUser).FirstOrDefault(s => s.Id == serviceId);
            ServiceDetails = _db.ServiceDetails.Where(s => s.ServiceHeaderId == serviceId).ToList();
        }
    }
}

SparkAuto5/Pages/Services/History.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using SparkAuto5.Data;
using SparkAuto5.Models;

namespace SparkAuto5.Pages.Services
{
    [Authorize]
    public class HistoryModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public HistoryModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public List<ServiceHeader> ServiceHeader { get; set; }
        public string UserId { get; set; }
        public async Task OnGet(int carId)
        {
            ServiceHeader = await _db.ServiceHeader
                .Include(s => s.Car)
                .Include(c => c.Car.ApplicationUser)
                .Where(c => c.CarId == carId)
                .ToListAsync();
            UserId = _db.Car.Where(u => u.Id == carId).ToList().FirstOrDefault().UserId;
        }
    }
}

SparkAuto5/Pages/Services/Create.cshtml
@page
@model SparkAuto5.Pages.Services.CreateModel
@{
    ViewData["Title"] = "Add Service";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container pt-4 pb-2 row">
    <div class="col-6">
        <h2 class="text-info py-2">Create Service</h2>
    </div>
    <div class="col-3 offset-3 text-right py-2">
        <a asp-page="../Cars/Index" asp-route-userId="@Model.CarServiceViewModel.Car.UserId" class="btn btn-outline-success form-control">
            Back to List
        </a>
    </div>
</div>
<div class="container background-white">
    <div class="card">
        <div class="card-header bg-dark text-light ml-0 row container">
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="far fa-user fa-2x"></i>
            </div>
            <div class="col-5">
                <label class="text-info">@Model.CarServiceViewModel.Car.ApplicationUser.Name</label><br />
                <label class="text-info">@Model.CarServiceViewModel.Car.ApplicationUser.Email | @Model.CarServiceViewModel.Car.ApplicationUser.PhoneNumber</label><br />
            </div>
            <div class="col-5 text-right">
                <label class="text-info">@Model.CarServiceViewModel.Car.Make @Model.CarServiceViewModel.Car.Model @Model.CarServiceViewModel.Car.Style</label><br />
                <label class="text-info">@Model.CarServiceViewModel.Car.Year</label>
            </div>
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="fas fa-car fa-2x"></i>
            </div>
        </div>
        <div class="card-body">
            <form method="post" style="width: 100%">
                <div class="container">
                    <input hidden asp-for="CarServiceViewModel.Car.Make" />
                    <input hidden asp-for="CarServiceViewModel.Car.Model" />
                    <input hidden asp-for="CarServiceViewModel.Car.VIN" />
                    <input hidden asp-for="CarServiceViewModel.Car.UserId" />
                    <input hidden asp-for="CarServiceViewModel.Car.Id" />

                    <div class="border rounded p-2">
                        <div class="row">
                            <div class="col-3">
                                <h4 class="text-info pl-3 pt-2 pb-1">Add Service</h4>
                            </div>
                            <div class="col-9 pb-1 pt-2">
                                <div class="row">
                                    <div class="col-8">
                                        <select asp-for="CarServiceViewModel.ServiceDetails.ServiceTypeId"
                                                asp-items="@(new SelectList(Model.CarServiceViewModel.ServiceTypesList,"Id","Name"))"
                                                class="form-control"></select>
                                    </div>
                                    <div class="col-4">
                                        <button type="submit" asp-page-handler="AddToCart" class="form-control btn btn-primary">
                                            Add
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <br />

                    <div class="border container rounded p-2">
                        <h3 class="text-info pb-2">Service Summary</h3>
                        @if (Model.CarServiceViewModel.ServiceShoppingCart.Count == 0)
                        {
                        <p>
                            Nobject service haside been added ydetails Please aaddress a service to bem performed.
                        </p>
                        }
                        else
                        {
                        <div class="row mt-3">
                            <div class="col-7">
                                <table class="table table-striped border">
                                    <tr class="table-secondary">
                                        <th>
                                            @Html.DisplayNameFor(m => Model.CarServiceViewModel.ServiceTypesList.FirstOrDefault().Name)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(m => Model.CarServiceViewModel.ServiceTypesList.FirstOrDefault().Price)
                                        </th>
                                        <th>

                                        </th>
                                    </tr>
                                    @foreach (var item in Model.CarServiceViewModel.ServiceShoppingCart)
                                        {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(m => item.ServiceType.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(m => item.ServiceType.Price)
                                        </td>
                                        <td>
                                            <button type="submit" asp-page-handler="RemoveFromCart" asp-route-serviceTypeId="@item.ServiceTypeId" class="btn btn-danger form-control">
                                                <i class="far fa-trash-alt"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    }
                                    <tr style="background-color:#e2fee2">
                                        <td colspan="1">
                                            <h6 class="text-success">Total Price</h6>
                                        </td>
                                        <td colspan="2">
                                            <h6 class="text-success">$@Model.CarServiceViewModel.ServiceHeader.TotalPrice</h6>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-5 px-4 pb-2">
                                <div class="row">
                                    <div class="col-4">
                                        <label asp-for="CarServiceViewModel.ServiceHeader.Kilometers" class="form-control" style="border:none;"></label>
                                    </div>
                                    <div class="col-8">
                                        <input asp-for="CarServiceViewModel.ServiceHeader.Kilometers" id="txtKilometers" class="form-control" />
                                    </div>
                                </div>
                                <div class="row py-2">
                                    <div class="col-12">
                                        <textarea placholder="Comments..." asp-for="CarServiceViewModel.ServiceHeader.Details" class="form-control" style="height:100px">
                                                                                    
                                        </textarea>
                                    </div>
                                </div>
                                <div class="row p-0">
                                    <div class="col-12">
                                        <button class="btn btn-success form-control" onclick="return validateInput()">Service Completed</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        function validateInput(){
            var kilometers = document.getElementById("txtKilometers").value;
            if (kilometers < 1){
                swal("Error!", "Kilometers cannot be empty or 0", "error");
                return false;
            }
        }
    </script>
}

SparkAuto5/Pages/Services/Details.cshtml
@page
@model SparkAuto5.Pages.Services.DetailsModel

@{
    ViewData["Title"] = "Service Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container pt-4 pb-2 row">
    <div class="col-6">
        <h2 class="text-info py-2">Create Service</h2>
    </div>
    <div class="col-3 offset-3 text-right py-2">
        <a asp-page="../Services/History" asp-route-carId="@Model.ServiceHeader.CarId" class="btn btn-outline-success form-control">
            Back to List
        </a>
    </div>
</div>
<div class="container background-white">
    <div class="card">
        <div class="card-header bg-dark text-light ml-0 row container">
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="far fa-user fa-2x"></i>
            </div>
            <div class="col-5">
                <label class="text-info">@Model.ServiceHeader.Car.ApplicationUser.Name</label><br />
                <label class="text-info">@Model.ServiceHeader.Car.ApplicationUser.Email | @Model.ServiceHeader.Car.ApplicationUser.PhoneNumber</label><br />
            </div>
            <div class="col-5 text-right">
                <label class="text-info">@Model.ServiceHeader.Car.Make @Model.ServiceHeader.Car.Model @Model.ServiceHeader.Car.Style</label><br />
                <label class="text-info">@Model.ServiceHeader.Car.Year</label>
            </div>
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="fas fa-car fa-2x"></i>
            </div>
        </div>
        <div class="card-body">
            <div class="row pt-3">
                <div class="col-7">
                    <table class="table table-striped border">
                        <tr class="table-secondary">
                            <th>
                                @Html.DisplayNameFor(m => Model.ServiceDetails[0].ServiceName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(m => Model.ServiceDetails[0].ServicePrice)
                            </th>
                        </tr>
                        @foreach (var item in Model.ServiceDetails)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.ServiceName)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.ServicePrice)
                            </td>
                        </tr>
                        }
                        <tr style="background-color:#e2fee2">
                            <td colspan="1">
                                <h6 class="text-success">Total Price</h6>
                            </td>
                            <td colspan="2">
                                <h6 class="text-success">$@Model.ServiceHeader.TotalPrice</h6>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="col-5 px-4 pb-2">
                    <div class="row">
                        <div class="col-4">
                            <label asp-for="ServiceHeader.Kilometers" class="form-control" style="border:none;"></label>
                        </div>
                        <div class="col-8">
                            <input asp-for="ServiceHeader.Kilometers" id="txtKilometers" class="form-control" readonly />
                        </div>
                    </div>
                    <div class="row py-2">
                        <div class="col-12">
                            <textarea placholder="Comments..." asp-for="ServiceHeader.Details" class="form-control" readonly style="height:100px">
                                                                                                                    
                            </textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SparkAuto5/Pages/Services/History.cshtml
@page
@model SparkAuto5.Pages.Services.HistoryModel
@{
    ViewData["Title"] = "Service History";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container pt-4 pb-2 row">
    <div class="col-6">
        <h2 class="text-info py-2">Service History</h2>
    </div>
    <div class="col-3 offset-3 text-right py-2">
        <a asp-page="../Cars/Index" asp-route-userId="@Model.UserId" class="btn btn-outline-success form-control">
            Back to List
        </a>
    </div>
</div>

@if (Model.ServiceHeader.Count == 0)
{
<div class="background-white">
    <p>
        No Service record found...
    </p>
</div>
}
else
{
<div class="container background-white">
    <div class="card">
        <div class="card-header bg-dark text-light ml-0 row container">
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="far fa-user fa-2x"></i>
            </div>
            <div class="col-5">
                <label class="text-info">@Model.ServiceHeader[0].Car.ApplicationUser.Name</label><br />
                <label class="text-info">@Model.ServiceHeader[0].Car.ApplicationUser.Email | @Model.ServiceHeader[0].Car.ApplicationUser.PhoneNumber</label><br />
            </div>
            <div class="col-5 text-right">
                <label class="text-info">@Model.ServiceHeader[0].Car.Make @Model.ServiceHeader[0].Car.Model @Model.ServiceHeader[0].Car.Style</label><br />
                <label class="text-info">@Model.ServiceHeader[0].Car.Year</label>
            </div>
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="fas fa-car fa-2x"></i>
            </div>
        </div>
        <div class="card-body">

            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        @Html.DisplayNameFor(m => Model.ServiceHeader[0].Kilometers)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => Model.ServiceHeader[0].TotalPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => Model.ServiceHeader[0].Details)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => Model.ServiceHeader[0].DateAdded)
                    </th>
                    <th>

                    </th>
                </tr>
                @foreach (var item in Model.ServiceHeader)
                    {
                <tr>
                    <td>
                        @Html.DisplayFor(m => item.Kilometers)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.TotalPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Details)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.DateAdded)
                    </td>
                    <td>
                        <a asp-page="Details" class="btn btn-info form-control" asp-route-serviceId="@item.Id">
                            <i class="fas fa-list-alt"></i> &nbsp; Details
                        </a>
                    </td>
                </tr>
                }
            </table>
        </div>
    </div>
</div>
}